fjohnson-instacartlite/config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  resources :users do
    resources :orders
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  constraints Clearance::Constraints::SignedIn.new do
    root to: 'users#dashboard', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'welcome#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

fjohnson-instacartlite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

fjohnson-instacartlite/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

fjohnson-instacartlite/app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :orders, dependent: :destroy
end

fjohnson-instacartlite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

fjohnson-instacartlite/app/controllers/orders_controller.rb
class OrdersController < ApplicationController

    before_action :set_user

    def index
        @orders = @user.orders.all
    end

    def show
        @order = @user.orders.find(params[:id])
    end

    def new
        @order = @user.orders.new
    end

    def create
        @user = User.find(params[:user_id])
        @order = @user.orders.create(order_params)
        redirect_to '/users/:user_id/orders/:id'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
        @user = current_user
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:date, :time, :address, :delivery_instructions)
    end

end

fjohnson-instacartlite/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :dashboard]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def dashboard
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    # respond_to do |format|
      if @user.save
        # format.html { 
          redirect_to sign_in_path, notice: 'User was successfully created.' # }
        # format.json { render :show, status: :created, location: @user }
      else
        # format.html { 
          render :new # }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    #end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :first_name, :last_name, :phone_number)
    end
end

fjohnson-instacartlite/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

fjohnson-instacartlite/app/helpers/application_helper.rb
module ApplicationHelper
end

fjohnson-instacartlite/app/helpers/orders_helper.rb
module OrdersHelper
end

fjohnson-instacartlite/app/helpers/users_helper.rb
module UsersHelper
end

fjohnson-instacartlite/app/helpers/welcome_helper.rb
module WelcomeHelper
end

fjohnson-instacartlite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instacartlite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

fjohnson-instacartlite/app/views/orders/_form.html.erb
<h1>Create Your Order</h1>

<%= form_for [@user, order] do |f| %>
  <div class="field">
    <%= f.label :delivery_date %>
    <%= f.text_field :date %>
  </div>

  <div class="field">
    <%= f.label :delivery_time %>
    <%= f.text_field :time %>
  </div>

  <div class="field">
    <%= f.label :delivery_address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :delivery_instructions %>
    <%= f.text_area :delivery_instructions %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

fjohnson-instacartlite/app/views/orders/index.html.erb
<h1>Your Orders</h1>

<% @user.orders.each do |order| %>
<div>
    <p><strong>Delivery Date: </strong><%= order.date %></p>
    <p><strong>Delivery Time: </strong><%= order.time %></p>
    <p><%= link_to "View Order Detail", "/users/:user_id/orders/:id" %></p>
</div>
<% end %>

fjohnson-instacartlite/app/views/orders/new.html.erb
<%= render partial: "form", locals: {order: @user.orders.new} %>

<%= link_to 'Back', user_orders_path(@user) %>

fjohnson-instacartlite/app/views/orders/show.html.erb
<h1>Your Order</h1>>

<h6>Delivery Date:</h6> <%= @order.date %>
<h6>Delivery Time:</h6> <%= @order.time %>
<h6>Delivery Address:</h6> <%= @order.address %>
<h6>Delivery Instructions: </h6><%= @order.delivery_instructions %>

<h5>Order Items</h5>
list of items will go here

<%= link_to 'Back', user_orders_path(@user) %>

fjohnson-instacartlite/app/views/users/_form.html.erb
<div class="field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>
</div>

<div class="field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name %>
</div>

<div class="field">
  <%= form.label :phone_number %>
  <%= form.text_field :phone_number %>
</div>

fjohnson-instacartlite/app/views/users/dashboard.html.erb
<div align="center">
    <h2>Hi, <%= @user.first_name %>!</h2>
</div>

<div align="center">
    <%= link_to 'My Account', '/users/show' %>
</div>

<div align="center">
    <%= link_to 'My Orders', '/users/:user_id/orders' %>
</div>

<div align="center">
    <%= link_to 'Create New Order', '/users/:user_id/orders/new' %>
</div>

fjohnson-instacartlite/app/views/users/edit.html.erb
<h1>Editing User</h1>

 <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>
<% end %>

<p><%= link_to 'Back', root_path %></p>

fjohnson-instacartlite/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

fjohnson-instacartlite/app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <h5><%= link_to 'Already have an account? Sign In.', sign_in_path %></h5>
    </div>
  <% end %>
</div>

fjohnson-instacartlite/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @user.phone_number %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', root_path %>

fjohnson-instacartlite/app/views/welcome/index.html.erb
<div align="center">
  <h1 style="color: rgb(46, 137, 19)">🥕 Instacart <i>Lite</i></h1>
  <h3>Groceries delivered in as lite-le as 1 hour</h3>
</div>

<div align="center">
   <p><%= link_to 'Sign up now!', sign_up_path %></p>
</div>

<div align="center">
   <p> <%= link_to 'Already have an account? Sign in.', sign_in_path %></p>
</div>